INC_DIRS := ../../include /usr/local/include/opencv4 /usr/include/opencv4
SRC_DIRS := ./
OBJ_DIR := ./obj
BIN_DIR := .
EXE_NAME := imgdnn.out

include ../../makefile.rules

LDFLAGS += -L/usr/local/lib -lopencv_stitching -lopencv_highgui -lopencv_imgcodecs -lopencv_dnn -lopencv_imgproc -lopencv_core
