INC_DIRS := ../../../include ../astar-bare
SRC_DIRS := ./ ../astar-bare
OBJ_DIR := ./obj
BIN_DIR := .
EXE_NAME := legged.out

include ../../../makefile.rules

CXXFLAGS += -Wno-delete-non-virtual-dtor
